basePath: /
definitions:
  model.Category:
    properties:
      description:
        type: string
      id:
        type: integer
      priority:
        type: integer
      status:
        type: boolean
    type: object
host: localhost:8080
info:
  contact:
    name: João Felipe
  description: This is a RESTful API in Go using Swagger
  title: GROCERY API
  version: "1.0"
paths:
  /categories:
    get:
      description: Returns all categories available in the system.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Category'
            type: array
      summary: List all categories
      tags:
      - Category
  /category:
    post:
      description: Create a new category
      parameters:
      - description: Dados da nova categoria
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/model.Category'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Category'
      summary: Create a new category
      tags:
      - Category
  /category/{id}:
    delete:
      description: Deletes the specified category
      parameters:
      - description: ID da Categoria
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Delatado com sucesso
          schema:
            type: string
      summary: Delete a category
      tags:
      - Category
    get:
      description: Returns the specified category
      parameters:
      - description: ID of Category
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Category'
      summary: List the category by id
      tags:
      - Category
  /category/change-status/{id}:
    put:
      description: Change the status of a category
      parameters:
      - description: ID da Categoria
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Category'
      summary: Change the status of a category
      tags:
      - Category
swagger: "2.0"
