basePath: /
definitions:
  model.Category:
    properties:
      description:
        type: string
      id:
        type: integer
      priority:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    name: João FElipe
  description: This is a RESTful API in Go using Swagger
  title: API MERCEARIA
  version: "1.0"
paths:
  /categories:
    get:
      description: Retorna todas as categorias disponíveis no sistema.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Category'
            type: array
      summary: Lista todas as categorias
      tags:
      - Categorias
swagger: "2.0"
